[project]
name = "criticker-to-letterboxd"
version = "0.1.0"
description = "Converts Criticker ratings to Letterboxd format"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
]
